### ISSUE TITLE
Keep chosen language QR code links

### ISSUE THREAD

**Issue by oren-z0** [Satoshi-Engineering/tip-cards#3]
Many people keep the default english language as their preferable language in their browser, instead of changing it to their native language. It would be great if the QR code links had some query param (i.e. `?lang=es`) that will set the language when the receiver opens the link. They can always change it in the language bar.

Consider moving the language bar to the top.

**Comment by dr-erych** [comment]
I would suggest to add an optional URL segment (for all routes). If set, disable the browser language detection and use the language from the url. 

**Idea for UI:** In the cards configuration we could add another select with label "Website language" and values "Use browser language", "English", "German", "Spanish", "Hebrew".  
Downside: This would add another control to the already quite big form that might be confusing for users that don't have the need.

As we are planning on adding individual landing pages, let's maybe combine the features?

**Comment by oren-z0** [comment]
I agree with the downside, it's too much to configure, and 99% of the times the preferred language of the person creating the card will match the person receiving the card.

Maybe the logic should follow something like:
1. On the first visit of the tipper to the website, he'll be redirected to the same page with `?lang=...` according to his `window.language`. If he changes the language, the `?lang=...` will change.
2. The generated QR codes will also have `?lang=...` in the link.
3. When the tip receiver enters the QR link, the website can check `window.languages` (plural) which represents all the languages that the viewer understands - for example in my computer it is `['en-US', 'en', 'he']`. If the language from the query param is not included in `window.languages`, a pop-up will ask the user if he wants to switch a language or remain with the query-param language or change it.

Also, the languages bar should show the full name of the languages (as spelled in the language):

Deutsche | English | Español | עברית

What do you think?

**Comment by dr-erych** [comment]
I talked to a few users and some of them really like the current behavior that they can just pre-print cards/QR codes and hand them out in any country (no matter which language the recipient speaks).

So, I would like to keep the current feature of detecting the browser language in place somehow, but maybe it doesn't need to be the default.

I was thinking about adding some "Advanced settings" section to the config form.

**Comment by dr-erych** [comment]
I implemented a first version of the requested feature:
* Initially if you visit the site, the language detection is set to "automatic detection" (use preferred browser language) and the same will be applied to the tip cards' QR codes.
* As soon as you manually change the language via the language switch in the footer:
  * It will get persisted in the URL (e.g. https://tipcards.io/he/...).
  * The links in the QR codes will also contain the language path segment.

**Comment by oren-z0** [comment]
Yes, this is great!
